### ISSUE TITLE
Option to hide “First time buying turnips” checkbox

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/islandtracker-feedback#2]
Hey. If I understand this checkbox correctly, it’s only to be used the first time you ever buy turnips, because that changes the calculation? After that, you’ll never need to tap it again. If so, could there be an option to hide the toggle?

**Comment by jamesmontemagno** [comment]
Yeah, i am curious to just hide it in general... or if they previously checked it then don't show again....

**Comment by ghost** [comment]
The only issue with having it vanish after being toggled is that you’d have to toggle it to do that, even if it wasn’t your first time. You could just hide it after you know someone has been using the app for a week maybe? Either way, thanks for considering!

**Comment by jamesmontemagno** [comment]
Should be fixed up in 1.2! new settings menu.

**Comment by ghost** [comment]
Download the update. Works beautifully!
