### ISSUE TITLE
Text at bottom of tracking page truncated

### ISSUE THREAD

**Issue by stevechadbourne** [jamesmontemagno/islandtracker-feedback#3]
On my iPhone X, text at the bottom of the tracking page has the bottom chopped off. I'm guessing it's the iPhone safe area pushing the bottom tab up over it.
![turnip1](https://user-images.githubusercontent.com/4307880/81511553-90df0d00-935d-11ea-8c98-2737b6495a18.png)

**Comment by jamesmontemagno** [comment]
Good find! Will get fixed up asap!

**Comment by jamesmontemagno** [comment]
Should be fixed up in 1.2
